version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root directory where package.json is located
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
