name: Superfan CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    # ✅ Web build (for deployment to Vercel/Netlify/Cloudflare Pages)
    - name: Build Expo Web
      run: npx expo export:web

    # ✅ Mobile builds with EAS
    - name: Install EAS CLI
      run: npm install -g eas-cli

    - name: Authenticate with Expo
      run: eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}

    # ⚡ Build preview APK/Simulator (internal distribution)
    - name: Build Preview (Android/iOS)
      run: eas build --platform all --profile preview --non-interactive

    # ⚡ Build production release (store-ready)
    - name: Build Production (Android/iOS)
      run: eas build --platform all --profile production --non-interactive

    # 🚀 Auto-submit to app stores (optional)
    - name: Submit to Stores
      run: eas submit --platform all --profile production --non-interactive
      if: github.ref == 'refs/heads/main'
